export const cliches = [
  {
    id: '1',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'A problem shared is a problem cut in half.',
    bookid: '1',
  },
  {
    id: '2',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Ask for help.',
    bookid: '1',
  },
  {
    id: '3',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Better them than me.',
    bookid: '1',
  },
  {
    id: '4',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Changing addictions is like switching seats on the Titanic.',
    bookid: '1',
  },
  {
    id: '5',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Do the footwork.',
    bookid: '1',
  },
  {
    id: '6',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Do the next right thing.',
    bookid: '1',
  },
  {
    id: '7',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Doing the deal.',
    bookid: '1',
  },
  {
    id: '8',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "Don't call me after you drink; call me before you drink.",
    bookid: '1',
  },
  {
    id: '9',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "Don't leave before the miracle happens.",
    bookid: '1',
  },
  {
    id: '10',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "Don't let other people's words define you.",
    bookid: '1',
  },
  {
    id: '11',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "Don't let people rent space in your head.",
    bookid: '1',
  },
  {
    id: '12',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "Don't think, don't drink, and go to meetings.",
    bookid: '1',
  },
  {
    id: '13',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Easy does it.',
    bookid: '1',
  },
  {
    id: '14',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'F.E.A.R. - False Evidence Appearing Real',
    bookid: '1',
  },
  {
    id: '15',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "Fake it 'till you make it.",
    bookid: '1',
  },
  {
    id: '16',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Feeling comfortable in your own skin.',
    bookid: '1',
  },
  {
    id: '17',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'First things first.',
    bookid: '1',
  },
  {
    id: '18',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Get out of yourself.',
    bookid: '1',
  },
  {
    id: '19',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'G.O.D. - Good Orderly Direction.',
    bookid: '1',
  },
  {
    id: '20',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'G.O.D. - Group of Drunks.',
    bookid: '1',
  },
  {
    id: '21',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "God doesn't give is what we want; God gives us what we need.",
    bookid: '1',
  },
  {
    id: '22',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Half measures availed us nothing.',
    bookid: '1',
  },
  {
    id: '23',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Have an attitude of gratitude.',
    bookid: '1',
  },
  {
    id: '24',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'H.O.W - Honest, Open, and Willing.',
    bookid: '1',
  },
  {
    id: '25',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "Ican't; He can; I think I'll let him.",
    bookid: '1',
  },
  {
    id: '26',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote:
      "I didn't get into trouble every time I drank; but every time I got in trouble I was drinking.",
    bookid: '1',
  },
  {
    id: '27',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'I have problems in areas where I used to not have any areas.',
    bookid: '1',
  },
  {
    id: '28',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'I was sick and tired of being sick and tired.',
    bookid: '1',
  },
  {
    id: '29',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'I was tired of the ass-kicking machine.',
    bookid: '1',
  },
  {
    id: '30',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "If I could drink like a normal person, I'd drink everyday.",
    bookid: '1',
  },
  {
    id: '31',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'If nothing changes, nothing changes.',
    bookid: '1',
  },
  {
    id: '32',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote:
      'If you are not completely satisfied with AA, your misery will be promptly refunded.',
    bookid: '1',
  },
  {
    id: '33',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "If you don't do a fourth, you'll probably drink a fifth.",
    bookid: '1',
  },
  {
    id: '34',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "If you don't drink, you won't get drunk.",
    bookid: '1',
  },
  {
    id: '35',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "If you don't get this program, stick around until it gets you.",
    bookid: '1',
  },
  {
    id: '36',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote:
      "If you don't have a sponsor, your addiction will gladly sponsor you.",
    bookid: '1',
  },
  {
    id: '37',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "If you don't remember your last drunk, you haven't had it yet.",
    bookid: '1',
  },
  {
    id: '38',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'If you hang out in a barbershop, you might just gey a haircut.',
    bookid: '1',
  },
  {
    id: '39',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote:
      "If you think you don't have a lower bottom, remember there' always a trap door.",
    bookid: '1',
  },
  {
    id: '40',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "If you're neck deep in shit, it's okay to piss your pants.",
    bookid: '1',
  },
  {
    id: '41',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'In sobriety, there are good times and growth times.',
    bookid: '1',
  },
  {
    id: '42',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote:
      'Insanity is doing the same thing over and over again expecting different results.',
    bookid: '1',
  },
  {
    id: '43',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote:
      "I doesn't matter what you think, or what you feel; it matters what you do.",
    bookid: '1',
  },
  {
    id: '44',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'It takes what it takes.',
    bookid: '1',
  },
  {
    id: '45',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'It works if you work it.',
    bookid: '1',
  },
  {
    id: '46',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "It's easier to put on slippers than carpet the world.",
    bookid: '1',
  },
  {
    id: '47',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote:
      "It's no fun having a belly full of alcohol, if you have a head full of AA.",
    bookid: '1',
  },
  {
    id: '48',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Keep coming back.',
    bookid: '1',
  },
  {
    id: '49',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Keep it simple.',
    bookid: '1',
  },
  {
    id: '50',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Let go and let God.',
    bookid: '1',
  },
  {
    id: '51',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Live and let Live.',
    bookid: '1',
  },
  {
    id: '52',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Look for the similarities, not at the differences.',
    bookid: '1',
  },
  {
    id: '53',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Meeting makers make it.',
    bookid: '1',
  },
  {
    id: '54',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'My disease wants to kill me.',
    bookid: '1',
  },
  {
    id: '55',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Ninety in ninety.',
    bookid: '1',
  },
  {
    id: '56',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'No 13th stepping.',
    bookid: '1',
  },
  {
    id: '57',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'No one comes into AA on a winning streak.',
    bookid: '1',
  },
  {
    id: '58',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'One day at a time.',
    bookid: '1',
  },
  {
    id: '59',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'One is too many and a thousand is not enough.',
    bookid: '1',
  },
  {
    id: '60',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Play the tape all the way through.',
    bookid: '1',
  },
  {
    id: '61',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Poor me, poor me, pour me another drink.',
    bookid: '1',
  },
  {
    id: '62',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Relapse is a process, not an event.',
    bookid: '1',
  },
  {
    id: '63',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Stark raving sober.',
    bookid: '1',
  },
  {
    id: '64',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Stay away from wet faces and wet places.',
    bookid: '1',
  },
  {
    id: '65',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Stick with the winners.',
    bookid: '1',
  },
  {
    id: '66',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "Stinkin' Thinkin'.",
    bookid: '1',
  },
  {
    id: '67',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Surrender to win.',
    bookid: '1',
  },
  {
    id: '68',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Take suggestions.',
    bookid: '1',
  },
  {
    id: '69',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Take the cotton wool out of your ears and put it in your mouth.',
    bookid: '1',
  },
  {
    id: '70',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'The first step is the only one you have to work perfectly.',
    bookid: '1',
  },
  {
    id: '71',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote:
      "There is only one thing you have to change - and that's everything.",
    bookid: '1',
  },
  {
    id: '72',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "They call it Alcohol-'ism', not Alcohol-'wasm'.",
    bookid: '1',
  },
  {
    id: '73',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "This disease is bigger than me, but it's not bigger than us.",
    bookid: '1',
  },
  {
    id: '74',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'This is a disease, not a disgrace.',
    bookid: '1',
  },
  {
    id: '75',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote:
      'This is a program for people who want it, not for people who need it.',
    bookid: '1',
  },
  {
    id: '76',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'This is a selfish program.',
    bookid: '1',
  },
  {
    id: '77',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'This is a simple program for complicated people.',
    bookid: '1',
  },
  {
    id: '78',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "This is a 'we' program.",
    bookid: '1',
  },
  {
    id: '79',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'This program is simple, not easy.',
    bookid: '1',
  },
  {
    id: '80',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'This too shall pass.',
    bookid: '1',
  },
  {
    id: '81',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Trust the process.',
    bookid: '1',
  },
  {
    id: '82',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Turn it over.',
    bookid: '1',
  },
  {
    id: '83',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Wait a year.',
    bookid: '1',
  },
  {
    id: '84',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote:
      'We are not bad people trying to get good, we are sick people trying to get well.',
    bookid: '1',
  },
  {
    id: '85',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "We don't trip over mountains; we trip over molehills.",
    bookid: '1',
  },
  {
    id: '86',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'We get sick by ourselves; we get well together.',
    bookid: '1',
  },
  {
    id: '87',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "We have a disease that tells us; we don't have a disease.",
    bookid: '1',
  },
  {
    id: '88',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote:
      "Whatever you put in front of your sobriety is the first thing you're going to lose.",
    bookid: '1',
  },
  {
    id: '89',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'When all else fails, working with another alcoholic saves the day.',
    bookid: '1',
  },
  {
    id: '90',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "When you get hit by a train, it's not the caboose that kills you.",
    bookid: '1',
  },
  {
    id: '91',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "Where's your higher power?",
    bookid: '1',
  },
  {
    id: '92',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'While you work on recovery, your addiction is doing push ups.',
    bookid: '1',
  },
  {
    id: '93',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Work the steps.',
    bookid: '1',
  },
  {
    id: '94',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "You can carry the message; you can't carry the alcoholic.",
    bookid: '1',
  },
  {
    id: '95',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "You can take a bath in champagne as long as you don't drink it.",
    bookid: '1',
  },
  {
    id: '96',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "You can't save your face and your ass at the same time.",
    bookid: '1',
  },
  {
    id: '97',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote:
      "You can't think your way into better living, but you can live your way into better thinking.",
    bookid: '1',
  },
  {
    id: '98',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "You don't go to a whorehouse to get a ham sandwich.",
    bookid: '1',
  },
  {
    id: '99',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'You have to give it away to keep it.',
    bookid: '1',
  },
  {
    id: '100',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: 'Your best thinking got you here.',
    bookid: '1',
  },
  {
    id: '101',
    book: '101 Common Cliches of Alcoholics Anonymous: The Sayings the Newcomers Hate and the Old-timers Love',
    quote: "You're on a pink cloud.",
    bookid: '1',
  },
];
