export const mymind = [
  {
    id: '1',
    book: 'My Mind Is Out To Get Me',
    quote: 'One day at a time.',
    bookid: '3',
  },
  {
    id: '2',
    book: 'My Mind Is Out To Get Me',
    quote: "You've got to give time, time.",
    bookid: '3',
  },
  {
    id: '3',
    book: 'My Mind Is Out To Get Me',
    quote:
      'Insanity: Doing exactly the same thing over and over, expecting different results.',
    bookid: '3',
  },
  {
    id: '4',
    book: 'My Mind Is Out To Get Me',
    quote:
      "It's a good meeting if no one gets drunk in the room during the meeting.",
    bookid: '3',
  },
  {
    id: '5',
    book: 'My Mind Is Out To Get Me',
    quote: 'H.A.L.T. - Hungry, Angry, Lonely, Tired.',
    bookid: '3',
  },
  {
    id: '6',
    book: 'My Mind Is Out To Get Me',
    quote:
      'The length of time away from a drink is not equal to the distance from a drink.',
    bookid: '3',
  },
  {
    id: '7',
    book: 'My Mind Is Out To Get Me',
    quote:
      'You have to be able to live with yourself before you can live with another person.',
    bookid: '3',
  },
  {
    id: '8',
    book: 'My Mind Is Out To Get Me',
    quote: "It's not what happens to you but how you perceive it.",
    bookid: '3',
  },
  {
    id: '9',
    book: 'My Mind Is Out To Get Me',
    quote:
      'Fourth Step: Fears, resentments, self-pities, guilts, hatreds, and whys.',
    bookid: '3',
  },
  {
    id: '10',
    book: 'My Mind Is Out To Get Me',
    quote: 'This too shall pass.',
    bookid: '3',
  },
  {
    id: '11',
    book: 'My Mind Is Out To Get Me',
    quote: 'Happiness is an inside job.',
    bookid: '3',
  },
  {
    id: '12',
    book: 'My Mind Is Out To Get Me',
    quote: 'Desparation, inspiration, perspiration.',
    bookid: '3',
  },
  {
    id: '13',
    book: 'My Mind Is Out To Get Me',
    quote: 'Keep it simple.',
    bookid: '3',
  },
  {
    id: '14',
    book: 'My Mind Is Out To Get Me',
    quote: 'Turn your will and your life over to God.',
    bookid: '3',
  },
  {
    id: '15',
    book: 'My Mind Is Out To Get Me',
    quote:
      "Don't drink even if your rear falls off; put it in a bag and bring it to the meeting.",
    bookid: '3',
  },
  {
    id: '16',
    book: 'My Mind Is Out To Get Me',
    quote: 'First things first.',
    bookid: '3',
  },
  {
    id: '17',
    book: 'My Mind Is Out To Get Me',
    quote: 'God never closes a door without also opening a window.',
    bookid: '3',
  },
  {
    id: '18',
    book: 'My Mind Is Out To Get Me',
    quote: 'Let go and let God.',
    bookid: '3',
  },
  {
    id: '19',
    book: 'My Mind Is Out To Get Me',
    quote: 'How important is it?',
    bookid: '3',
  },
  {
    id: '20',
    book: 'My Mind Is Out To Get Me',
    quote:
      'Coincedence: God performs a little miracle and wishes to remain anonymous.',
    bookid: '3',
  },
  {
    id: '21',
    book: 'My Mind Is Out To Get Me',
    quote: "Utilise, don't analyse.",
    bookid: '3',
  },
  {
    id: '22',
    book: 'My Mind Is Out To Get Me',
    quote: 'An AA member is just a drunk with a conscience.',
    bookid: '3',
  },
  {
    id: '23',
    book: 'My Mind Is Out To Get Me',
    quote: 'Platitudes can help with your attitudes.',
    bookid: '3',
  },
  {
    id: '24',
    book: 'My Mind Is Out To Get Me',
    quote: 'Ninety meetings in ninety days.',
    bookid: '3',
  },
  {
    id: '25',
    book: 'My Mind Is Out To Get Me',
    quote:
      "There's nothing wrong with pursuing happiness, just don't get angry if it eludes you.",
    bookid: '3',
  },
  {
    id: '26',
    book: 'My Mind Is Out To Get Me',
    quote: 'Do the rowing and let God do the steering.',
    bookid: '3',
  },
  {
    id: '27',
    book: 'My Mind Is Out To Get Me',
    quote: 'Alcohol tried to murder my soul.',
    bookid: '3',
  },
  {
    id: '28',
    book: 'My Mind Is Out To Get Me',
    quote: "Treat your mind like a bad neighbourhood -- don't go there alone.",
    bookid: '3',
  },
  {
    id: '29',
    book: 'My Mind Is Out To Get Me',
    quote: "Ten out of ten people die, so don't take life so seriously.",
    bookid: '3',
  },
  {
    id: '30',
    book: 'My Mind Is Out To Get Me',
    quote:
      "Only three things happen to alcoholics who don't stop drinking: They get screwed up, locked up, or covered up.",
    bookid: '3',
  },
  {
    id: '31',
    book: 'My Mind Is Out To Get Me',
    quote: 'You have to love yourself before you can love yourself.',
    bookid: '3',
  },
  {
    id: '32',
    book: 'My Mind Is Out To Get Me',
    quote:
      "When I have a dollar more than what I need, I'm rich. Before I quit drinking, I was always a dollar short.",
    bookid: '3',
  },
  {
    id: '33',
    book: 'My Mind Is Out To Get Me',
    quote: "You don't die when you get ready, you die when God gets ready.",
    bookid: '3',
  },
  {
    id: '34',
    book: 'My Mind Is Out To Get Me',
    quote: "Stand for something or you'll fall for anything.",
    bookid: '3',
  },
  {
    id: '35',
    book: 'My Mind Is Out To Get Me',
    quote: "Your actions are so loud I can't hear what you're saying.",
    bookid: '3',
  },
  {
    id: '36',
    book: 'My Mind Is Out To Get Me',
    quote:
      "Yesterday is so far in the past I can't see it; tomorrow is too distant in the future to be seen. So I'll take a good look at what I can see - today.",
    bookid: '3',
  },
  {
    id: '37',
    book: 'My Mind Is Out To Get Me',
    quote: 'Keep coming back.',
    bookid: '3',
  },
  {
    id: '38',
    book: 'My Mind Is Out To Get Me',
    quote: 'Live like this is the last day of your life.',
    bookid: '3',
  },
  {
    id: '39',
    book: 'My Mind Is Out To Get Me',
    quote: 'S.L.I.P. - Sobriety Loses Its Priority.',
    bookid: '3',
  },
  {
    id: '40',
    book: 'My Mind Is Out To Get Me',
    quote:
      'The best fringe benefit of being in AA is that you never have to be alone again.',
    bookid: '3',
  },
  {
    id: '41',
    book: 'My Mind Is Out To Get Me',
    quote: 'Wear the world as a loose garment.',
    bookid: '3',
  },
  {
    id: '42',
    book: 'My Mind Is Out To Get Me',
    quote: 'Give yourself a little success every day.',
    bookid: '3',
  },
  {
    id: '43',
    book: 'My Mind Is Out To Get Me',
    quote: 'Only one in ten alcoholics die sober. Beat the odds.',
    bookid: '3',
  },
  {
    id: '44',
    book: 'My Mind Is Out To Get Me',
    quote: 'I am responsible.',
    bookid: '3',
  },
  {
    id: '45',
    book: 'My Mind Is Out To Get Me',
    quote: 'But for the grace of God...',
    bookid: '3',
  },
  {
    id: '46',
    book: 'My Mind Is Out To Get Me',
    quote: 'Be profound, funny, or quiet.',
    bookid: '3',
  },
  {
    id: '47',
    book: 'My Mind Is Out To Get Me',
    quote: 'Trust God, clean house, and help others.',
    bookid: '3',
  },
  {
    id: '48',
    book: 'My Mind Is Out To Get Me',
    quote: "God doesn't make mistakes.",
    bookid: '3',
  },
  {
    id: '49',
    book: 'My Mind Is Out To Get Me',
    quote: 'Any excuse for a drink is as good as any excuse for a drink.',
    bookid: '3',
  },
  {
    id: '50',
    book: 'My Mind Is Out To Get Me',
    quote: 'When tragic things begin to seem funny, health has begun.',
    bookid: '3',
  },
  {
    id: '51',
    book: 'My Mind Is Out To Get Me',
    quote: 'Easy does it.',
    bookid: '3',
  },
  {
    id: '52',
    book: 'My Mind Is Out To Get Me',
    quote: 'After you talk in a meeting, listen to hear if you said anything.',
    bookid: '3',
  },
  {
    id: '53',
    book: 'My Mind Is Out To Get Me',
    quote: "We're all doing the best we can.",
    bookid: '3',
  },
  {
    id: '54',
    book: 'My Mind Is Out To Get Me',
    quote: 'Easy does it, but do it.',
    bookid: '3',
  },
  {
    id: '55',
    book: 'My Mind Is Out To Get Me',
    quote: 'I may have a drink tomorrow, but not today.',
    bookid: '3',
  },
  {
    id: '56',
    book: 'My Mind Is Out To Get Me',
    quote: 'Fake it till you make it.',
    bookid: '3',
  },
  {
    id: '57',
    book: 'My Mind Is Out To Get Me',
    quote:
      'Put your desire chip under your tongue; when it melts, you can have a drink.',
    bookid: '3',
  },
  {
    id: '58',
    book: 'My Mind Is Out To Get Me',
    quote:
      'For an alcoholic, one drink is one too many - one thousand is not enough.',
    bookid: '3',
  },
  {
    id: '59',
    book: 'My Mind Is Out To Get Me',
    quote: 'Never underestimate the power of prayer or the passage of time.',
    bookid: '3',
  },
  {
    id: '60',
    book: 'My Mind Is Out To Get Me',
    quote: 'Meeting makers make it.',
    bookid: '3',
  },
  {
    id: '61',
    book: 'My Mind Is Out To Get Me',
    quote: 'No one can make you take a drink, and no one can make you stop.',
    bookid: '3',
  },
  {
    id: '62',
    book: 'My Mind Is Out To Get Me',
    quote: 'Why drink today when you can putit off until tomorrow?',
    bookid: '3',
  },
  {
    id: '63',
    book: 'My Mind Is Out To Get Me',
    quote: 'You have to be willing to participate in your own recovery.',
    bookid: '3',
  },
  {
    id: '64',
    book: 'My Mind Is Out To Get Me',
    quote: 'A lot of people have died wanting to get sober.',
    bookid: '3',
  },
  {
    id: '65',
    book: 'My Mind Is Out To Get Me',
    quote:
      "The great paradox of spirituality is that you've got to give it away to keep it.",
    bookid: '3',
  },
  {
    id: '66',
    book: 'My Mind Is Out To Get Me',
    quote:
      'This program is a marriage of hope and action, and it has to be both.',
    bookid: '3',
  },
  {
    id: '67',
    book: 'My Mind Is Out To Get Me',
    quote: "I don't need your help today. Love, God.",
    bookid: '3',
  },
  {
    id: '68',
    book: 'My Mind Is Out To Get Me',
    quote:
      "In the first year of sobriety, don't change anything except your playmates, playthings, and playgrounds.",
    bookid: '3',
  },
  {
    id: '69',
    book: 'My Mind Is Out To Get Me',
    quote: "Stinkin' thinkin' leads to drinkin'.",
    bookid: '3',
  },
  {
    id: '70',
    book: 'My Mind Is Out To Get Me',
    quote: "Drinkin' leads to stinkin' thinkin'.",
    bookid: '3',
  },
  {
    id: '71',
    book: 'My Mind Is Out To Get Me',
    quote: 'Slippery people and slippery places lead to slips.',
    bookid: '3',
  },
  {
    id: '72',
    book: 'My Mind Is Out To Get Me',
    quote: 'It works if you work it.',
    bookid: '3',
  },
  {
    id: '73',
    book: 'My Mind Is Out To Get Me',
    quote: "Today is the yesterday you'll worry about tomorrow.",
    bookid: '3',
  },
  {
    id: '74',
    book: 'My Mind Is Out To Get Me',
    quote: 'AA is a simple program for complicated people.',
    bookid: '3',
  },
  {
    id: '75',
    book: 'My Mind Is Out To Get Me',
    quote: "AA is not where you wind up, it's where you start over.",
    bookid: '3',
  },
  {
    id: '76',
    book: 'My Mind Is Out To Get Me',
    quote: 'Our sickness is between our ears.',
    bookid: '3',
  },
  {
    id: '77',
    book: 'My Mind Is Out To Get Me',
    quote: 'It takes time.',
    bookid: '3',
  },
  {
    id: '78',
    book: 'My Mind Is Out To Get Me',
    quote: "You aren't going to get it by Thursday.",
    bookid: '3',
  },
  {
    id: '79',
    book: 'My Mind Is Out To Get Me',
    quote: 'An empty can makes the most noise.',
    bookid: '3',
  },
  {
    id: '80',
    book: 'My Mind Is Out To Get Me',
    quote: 'Every AA meeting is a payment on your sobriety.',
    bookid: '3',
  },
  {
    id: '81',
    book: 'My Mind Is Out To Get Me',
    quote: 'Alcoholics have three choices: die, go nuts, or get sober.',
    bookid: '3',
  },
  {
    id: '82',
    book: 'My Mind Is Out To Get Me',
    quote:
      "God can't hand you anything new until you let go of what you're holding.",
    bookid: '3',
  },
  {
    id: '83',
    book: 'My Mind Is Out To Get Me',
    quote:
      "Carry your strength, hope, and experience to those people you find attractive and, especially, to those you don't.",
    bookid: '3',
  },
  {
    id: '84',
    book: 'My Mind Is Out To Get Me',
    quote: "When I think I'm out of control, I'm most out of control.",
    bookid: '3',
  },
  {
    id: '85',
    book: 'My Mind Is Out To Get Me',
    quote:
      'There are many ways to cross the river - what matters is that you cross sober.',
    bookid: '3',
  },
  {
    id: '86',
    book: 'My Mind Is Out To Get Me',
    quote:
      "I learning to be sober doesn't feel awkward, you're not making progress.",
    bookid: '3',
  },
  {
    id: '87',
    book: 'My Mind Is Out To Get Me',
    quote:
      "If you don't change, you don't grow. And if you don't grow, you don't go.",
    bookid: '3',
  },
  {
    id: '88',
    book: 'My Mind Is Out To Get Me',
    quote:
      "Alcoholics are self-adoring egotists who can't stand their own image.",
    bookid: '3',
  },
  {
    id: '89',
    book: 'My Mind Is Out To Get Me',
    quote:
      'To stay sober, you must make the abnormal normal, and the normal abnormal.',
    bookid: '3',
  },
  {
    id: '90',
    book: 'My Mind Is Out To Get Me',
    quote: 'If you keep bringing your body, your mind will follow.',
    bookid: '3',
  },
  {
    id: '91',
    book: 'My Mind Is Out To Get Me',
    quote: 'Alcoholism is the high cost of low living.',
    bookid: '3',
  },
  {
    id: '92',
    book: 'My Mind Is Out To Get Me',
    quote: 'When confronted with a dilemma, ask yourself, What would God do?',
    bookid: '3',
  },
  {
    id: '93',
    book: 'My Mind Is Out To Get Me',
    quote: "If you think you have humility, you don't.",
    bookid: '3',
  },
  {
    id: '94',
    book: 'My Mind Is Out To Get Me',
    quote:
      "If others did the things to us that we as alcoholics do to ourselves, we'd kill them.",
    bookid: '3',
  },
  {
    id: '95',
    book: 'My Mind Is Out To Get Me',
    quote:
      'AA is not a place to go to save your soul but if you have an open mind, you may save your skin.',
    bookid: '3',
  },
  {
    id: '96',
    book: 'My Mind Is Out To Get Me',
    quote: 'I got drunk alone. In AA we get sober together.',
    bookid: '3',
  },
  {
    id: '97',
    book: 'My Mind Is Out To Get Me',
    quote: "In God's sight, all human beings are important.",
    bookid: '3',
  },
  {
    id: '98',
    book: 'My Mind Is Out To Get Me',
    quote: 'Walk your talk.',
    bookid: '3',
  },
  {
    id: '99',
    book: 'My Mind Is Out To Get Me',
    quote: 'Once you give love, you receive love.',
    bookid: '3',
  },
  {
    id: '100',
    book: 'My Mind Is Out To Get Me',
    quote: 'You get back what you give out.',
    bookid: '3',
  },
  {
    id: '101',
    book: 'My Mind Is Out To Get Me',
    quote: "You aren't responsible for anyone's happiness but your own.",
    bookid: '3',
  },
  {
    id: '102',
    book: 'My Mind Is Out To Get Me',
    quote: 'You attract what you were.',
    bookid: '3',
  },
  {
    id: '103',
    book: 'My Mind Is Out To Get Me',
    quote: 'There are no mistakes, just learning experiences.',
    bookid: '3',
  },
  {
    id: '104',
    book: 'My Mind Is Out To Get Me',
    quote: 'Want to hear God laugh? Tell him your plans.',
    bookid: '3',
  },
  {
    id: '105',
    book: 'My Mind Is Out To Get Me',
    quote:
      'Humility is not thinking less of yourself, it is thinking of yourself less often.',
    bookid: '3',
  },
  {
    id: '106',
    book: 'My Mind Is Out To Get Me',
    quote: 'Alcoholics all drink for the same reason - any reason.',
    bookid: '3',
  },
  {
    id: '107',
    book: 'My Mind Is Out To Get Me',
    quote: 'Some days are diamonds, others just rough stones.',
    bookid: '3',
  },
  {
    id: '108',
    book: 'My Mind Is Out To Get Me',
    quote: 'Get out of the problem and into a solution.',
    bookid: '3',
  },
  {
    id: '109',
    book: 'My Mind Is Out To Get Me',
    quote: "Live life on life's terms.",
    bookid: '3',
  },
  {
    id: '110',
    book: 'My Mind Is Out To Get Me',
    quote:
      "Don't expect to learn about people from books; a person can't fit in a bookcase.",
    bookid: '3',
  },
  {
    id: '111',
    book: 'My Mind Is Out To Get Me',
    quote: 'When I react to someone, that person becomes my Higher Power.',
    bookid: '3',
  },
  {
    id: '112',
    book: 'My Mind Is Out To Get Me',
    quote:
      'When you need something in your life to replace alcohol, work a step.',
    bookid: '3',
  },
  {
    id: '113',
    book: 'My Mind Is Out To Get Me',
    quote: 'My recovery is a process, not an event.',
    bookid: '3',
  },
  {
    id: '114',
    book: 'My Mind Is Out To Get Me',
    quote: 'HOW? Honesty, Open-mindedness, Willingness',
    bookid: '3',
  },
  {
    id: '115',
    book: 'My Mind Is Out To Get Me',
    quote: 'Do good, be good, and God will be with you.',
    bookid: '3',
  },
  {
    id: '116',
    book: 'My Mind Is Out To Get Me',
    quote:
      'At meetings, leave your credentials and your intellect at the door.',
    bookid: '3',
  },
  {
    id: '117',
    book: 'My Mind Is Out To Get Me',
    quote:
      "If you make a twelfth step call and you don't drink, it's successful.",
    bookid: '3',
  },
  {
    id: '118',
    book: 'My Mind Is Out To Get Me',
    quote:
      "Twelfth Step: If they're ready, you can't say anything wrong. If they're not, you can't say anything right.",
    bookid: '3',
  },
  {
    id: '119',
    book: 'My Mind Is Out To Get Me',
    quote: 'Alcohol is patient; your disease will wait for you forever.',
    bookid: '3',
  },
  {
    id: '120',
    book: 'My Mind Is Out To Get Me',
    quote: 'Life is slippery when wet.',
    bookid: '3',
  },
  {
    id: '121',
    book: 'My Mind Is Out To Get Me',
    quote: 'Let it begin with me.',
    bookid: '3',
  },
  {
    id: '122',
    book: 'My Mind Is Out To Get Me',
    quote: "We've each got our own self-improvement kit.",
    bookid: '3',
  },
  {
    id: '123',
    book: 'My Mind Is Out To Get Me',
    quote: 'Learn to listen so that you can listen to learn.',
    bookid: '3',
  },
  {
    id: '124',
    book: 'My Mind Is Out To Get Me',
    quote: "You never know what you're addicted to until you stop.",
    bookid: '3',
  },
  {
    id: '125',
    book: 'My Mind Is Out To Get Me',
    quote: "It's alright to plan; just don't plan the results.",
    bookid: '3',
  },
  {
    id: '126',
    book: 'My Mind Is Out To Get Me',
    quote: 'Fear is the absence of faith.',
    bookid: '3',
  },
  {
    id: '127',
    book: 'My Mind Is Out To Get Me',
    quote:
      'The bad news: Nobody is coming to rescue you. The good news: You can save yourself.',
    bookid: '3',
  },
  {
    id: '128',
    book: 'My Mind Is Out To Get Me',
    quote: "I don't ever want to have to stop drinking again.",
    bookid: '3',
  },
  {
    id: '129',
    book: 'My Mind Is Out To Get Me',
    quote: 'I can never help another alcoholic without helping myself.',
    bookid: '3',
  },
  {
    id: '130',
    book: 'My Mind Is Out To Get Me',
    quote: "I am where I am because that's where I am supposed to be.",
    bookid: '3',
  },
  {
    id: '131',
    book: 'My Mind Is Out To Get Me',
    quote: 'The long journey to sobriety begins where you are.',
    bookid: '3',
  },
  {
    id: '132',
    book: 'My Mind Is Out To Get Me',
    quote: 'Tranquilisers are nothing more than solid alcohol.',
    bookid: '3',
  },
  {
    id: '133',
    book: 'My Mind Is Out To Get Me',
    quote: 'Pass it on.',
    bookid: '3',
  },
  {
    id: '134',
    book: 'My Mind Is Out To Get Me',
    quote: 'I have a choice.',
    bookid: '3',
  },
  {
    id: '135',
    book: 'My Mind Is Out To Get Me',
    quote: "The Twelve Steps are God's gift to the twentieth century.",
    bookid: '3',
  },
  {
    id: '136',
    book: 'My Mind Is Out To Get Me',
    quote:
      'Before I came to AA, I never realised how bad my life was or how good it could be.',
    bookid: '3',
  },
  {
    id: '137',
    book: 'My Mind Is Out To Get Me',
    quote: 'Alcohol: Ignorant oil.',
    bookid: '3',
  },
  {
    id: '138',
    book: 'My Mind Is Out To Get Me',
    quote: "I'm here because I don't want to live like I used to live.",
    bookid: '3',
  },
  {
    id: '139',
    book: 'My Mind Is Out To Get Me',
    quote:
      'There is little you can count on in life except feeling bad after that first drink.',
    bookid: '3',
  },
  {
    id: '140',
    book: 'My Mind Is Out To Get Me',
    quote: 'Long sobriety does not mean greater immunity from drinking again.',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
  {
    id: '',
    book: 'My Mind Is Out To Get Me',
    quote: '',
    bookid: '3',
  },
];
