export const sobercards = [
  {
    id: 'A Hearts',
    book: 'Sober Cards',
    quote: 'Live and let live.',
    bookid: '4',
  },
  {
    id: '2 Hearts',
    book: 'Sober Cards',
    quote: 'Keep recovery first to make it your last.',
    bookid: '4',
  },
  {
    id: '3 Hearts',
    book: 'Sober Cards',
    quote: "Don't let people rent space in your head.",
    bookid: '4',
  },
  {
    id: '4 Hearts',
    book: 'Sober Cards',
    quote: 'Nothing changes if nothing changes.',
    bookid: '4',
  },
  {
    id: '5 Hearts',
    book: 'Sober Cards',
    quote:
      'We either make ourselves miserable or make ourselves stronger, the amount of work is the same.',
    bookid: '4',
  },
  {
    id: '6 Hearts',
    book: 'Sober Cards',
    quote: 'Faith without works is dead.',
    bookid: '4',
  },
  {
    id: '7 Hearts',
    book: 'Sober Cards',
    quote: 'KISS: Keep It Simple Stupid.',
    bookid: '4',
  },
  {
    id: '8 Hearts',
    book: 'Sober Cards',
    quote: 'To thine own self be true.',
    bookid: '4',
  },
  {
    id: '9 Hearts',
    book: 'Sober Cards',
    quote: "Before you say I can't, say I'll try.",
    bookid: '4',
  },
  {
    id: '10 Hearts',
    book: 'Sober Cards',
    quote: 'Trying to pray is praying.',
    bookid: '4',
  },
  {
    id: 'Jack Hearts',
    book: 'Sober Cards',
    quote: 'Some things are true whether you believe them or not.',
    bookid: '4',
  },
  {
    id: 'Queen Hearts',
    book: 'Sober Cards',
    quote: 'One hour at a time, one day at a time, one step at a time.',
    bookid: '4',
  },
  {
    id: 'King Hearts',
    book: 'Sober Cards',
    quote: 'It gets real, it gets different, it gets real different.',
    bookid: '4',
  },
  {
    id: 'A Clubs',
    book: 'Sober Cards',
    quote: 'One day at a time.',
    bookid: '4',
  },
  {
    id: '2 Clubs',
    book: 'Sober Cards',
    quote: 'Keep coming back. It works if you work it.',
    bookid: '4',
  },
  {
    id: '3 Clubs',
    book: 'Sober Cards',
    quote: "Don't quit before the miracle happens.",
    bookid: '4',
  },
  {
    id: '4 Clubs',
    book: 'Sober Cards',
    quote: 'We are only as sick as our secrets.',
    bookid: '4',
  },
  {
    id: '5 Clubs',
    book: 'Sober Cards',
    quote: 'Willingness is the key.',
    bookid: '4',
  },
  {
    id: '6 Clubs',
    book: 'Sober Cards',
    quote:
      "Serenity isn't freedom from the storm. It's peace within the storm.",
    bookid: '4',
  },
  {
    id: '7 Clubs',
    book: 'Sober Cards',
    quote: 'Love and tolerance is our code.',
    bookid: '4',
  },
  {
    id: '8 Clubs',
    book: 'Sober Cards',
    quote: 'Easy does it.',
    bookid: '4',
  },
  {
    id: '9 Clubs',
    book: 'Sober Cards',
    quote: "Don't be bitter, be better.",
    bookid: '4',
  },
  {
    id: '10 Clubs',
    book: 'Sober Cards',
    quote: "Remember, it's progress not perfection.",
    bookid: '4',
  },
  {
    id: 'Jack Clubs',
    book: 'Sober Cards',
    quote: 'One drink is too many and a thousand is not enough.',
    bookid: '4',
  },
  {
    id: 'Queen Clubs',
    book: 'Sober Cards',
    quote: 'Stick with the winners.',
    bookid: '4',
  },
  {
    id: 'King Clubs',
    book: 'Sober Cards',
    quote: 'If I could drink like other people I would drink all the time.',
    bookid: '4',
  },
  {
    id: 'A Diamonds',
    book: 'Sober Cards',
    quote: "Idle hands are the devil's playground.",
    bookid: '4',
  },
  {
    id: '2 Diamonds',
    book: 'Sober Cards',
    quote: 'First things first.',
    bookid: '4',
  },
  {
    id: '3 Diamonds',
    book: 'Sober Cards',
    quote: 'More will be revealed.',
    bookid: '4',
  },
  {
    id: '4 Diamonds',
    book: 'Sober Cards',
    quote: 'This too shall pass.',
    bookid: '4',
  },
  {
    id: '5 Diamonds',
    book: 'Sober Cards',
    quote: 'Do the next right thing.',
    bookid: '4',
  },
  {
    id: '6 Diamonds',
    book: 'Sober Cards',
    quote: 'Peace and serenity through surrender.',
    bookid: '4',
  },
  {
    id: '7 Diamonds',
    book: 'Sober Cards',
    quote: "Don't borrow trouble from tomorrow.",
    bookid: '4',
  },
  {
    id: '8 Diamonds',
    book: 'Sober Cards',
    quote: "Don't take everything so personally.",
    bookid: '4',
  },
  {
    id: '9 Diamonds',
    book: 'Sober Cards',
    quote: 'Play the tape out.',
    bookid: '4',
  },
  {
    id: '10 Diamonds',
    book: 'Sober Cards',
    quote: 'Instead of saying I have to; say, "I get to."',
    bookid: '4',
  },
  {
    id: 'Jack Diamonds',
    book: 'Sober Cards',
    quote: "Rule#62: Don't take yourself too damn seriously.",
    bookid: '4',
  },
  {
    id: 'Queen Diamonds',
    book: 'Sober Cards',
    quote: 'Sometimes quickly, sometimes slowly.',
    bookid: '4',
  },
  {
    id: 'King Diamonds',
    book: 'Sober Cards',
    quote:
      'What is the loving and giving action I can do, right here and now in this situation.',
    bookid: '4',
  },
  {
    id: 'A Spades',
    book: 'Sober Cards',
    quote: "Just don't drink.",
    bookid: '4',
  },
  {
    id: '2 Spades',
    book: 'Sober Cards',
    quote: 'When one door closes, another one opens.',
    bookid: '4',
  },
  {
    id: '3 Spades',
    book: 'Sober Cards',
    quote: 'God is never late.',
    bookid: '4',
  },
  {
    id: '4 Spades',
    book: 'Sober Cards',
    quote: 'Thy will not mine, be done.',
    bookid: '4',
  },
  {
    id: '5 Spades',
    book: 'Sober Cards',
    quote: 'Stay sober for yourself.',
    bookid: '4',
  },
  {
    id: '6 Spades',
    book: 'Sober Cards',
    quote: 'Resting on our laurels, we are in trouble if we do.',
    bookid: '4',
  },
  {
    id: '7 Spades',
    book: 'Sober Cards',
    quote: "If you're feeling guilty, you probably are.",
    bookid: '4',
  },
  {
    id: '8 Spades',
    book: 'Sober Cards',
    quote: 'Start missing meetings and you start missing drinks.',
    bookid: '4',
  },
  {
    id: '9 Spades',
    book: 'Sober Cards',
    quote: 'Character is how we act when no one is watching.',
    bookid: '4',
  },
  {
    id: '10 Spades',
    book: 'Sober Cards',
    quote: 'Sobriety is a journey, not a destination.',
    bookid: '4',
  },
  {
    id: 'Jack Spades',
    book: 'Sober Cards',
    quote: 'Be part of the solution, not the problem.',
    bookid: '4',
  },
  {
    id: 'Queen Spades',
    book: 'Sober Cards',
    quote: 'Let go and let God.',
    bookid: '4',
  },
  {
    id: 'King Spades',
    book: 'Sober Cards',
    quote: 'Live in the now, look for the now, accept the good.',
    bookid: '4',
  },
];
